# Generated by Django 2.2.28 on 2023-06-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='dfghj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
